apiVersion: v1
kind: Pod
metadata:
  name: rer-savia-retriever
  namespace: rer-savia
spec:
  containers:
    - command: ["/bin/sh","-c"]
      args: 
      -  echo "mongo_db mongo-db" > /etc/host.aliases;
         export HOSTALIASES=/etc/host.aliases;
         apt-get -y install vim
         python flask_client.py
      image: harbor-core.prod.margherita.ad.lepida.it/savia-test/test_savia_retriever:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5001
      volumeMounts:
      - mountPath: /checkpoints
        name: checkpoints
      - mountPath: /retriever
        name: retriever
      - mountPath: /SAVIA_vector_stores
        name: savia-vector-stores
      name: savia-test-retriever
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: 30Gi
          cpu: "16"
        requests:
          memory: 8Gi
          cpu: "8"
  volumes:
  - name: checkpoints
    persistentVolumeClaim: 
      claimName: checkpoints
  - name: retriever
    persistentVolumeClaim: 
      claimName: retriever
  - name: savia-vector-stores
    persistentVolumeClaim: 
      claimName: savia-vector-stores
  
  metadata:
    namespace: rer-savia
  runtimeClassName: nvidia
