apiVersion: v1
kind: Pod
metadata:
  name: rer-savia-python-client
  namespace: rer-savia
spec:
  containers:
    - command: ["/bin/sh","-c"]
      args: ["sleep infinity"]
      image: harbor-core.prod.margherita.ad.lepida.it/savia-test/test_savia_python_client:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8897
      volumeMounts:
      - mountPath: /python_client
        name: python-client
      name: savia-test-python-client
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        limits:
          memory: 30Gi
          cpu: "16"
        requests:
          memory: 8Gi
          cpu: "8"
  volumes:
  - name: python-client
    persistentVolumeClaim: 
      claimName: python-client
  metadata:
    namespace: rer-savia
  runtimeClassName: nvidia
