apiVersion: apps/v1
kind: Deployment
metadata:
  name: savia-rer-sanita-laemur
  labels:
    app: savia-rer-sanita-laemur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savia-rer-sanita-laemur
  template:
    metadata:
      labels:
        app: savia-rer-sanita-laemur
    spec:
      containers:
        - name: savia-rer-sanita-laemur
          image: nvidia/cuda
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - mkdir /rer_app;
              cd rer_app/;
              git init;
              git remote add origin https://github.com/Peppesergee/savia-test.git;
              git branch -M main;
              git pull origin main;
              pip install uvicorn;
              pip install fastapi;
              pip install transformers;
              pip install torch;
              pip install 'accelerate>=0.26.0';
              pip install bitsandbytes;
              cd application_code/;
              uvicorn test_api:app --host 0.0.0.0 --port 8000 --reload;
          workingDir: "/"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
