apiVersion: apps/v1
kind: Deployment
metadata:
  name: savia-rer-sanita-laemur
  labels:
    app: savia-rer-sanita-laemur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savia-rer-sanita-laemur
  template:
    metadata:
      labels:
        app: savia-rer-sanita-laemur
    spec:
      containers:
        - name: savia-rer-sanita-laemur
          image: nvidia/cuda:12.6.1-devel-ubuntu24.04
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep"]
          args: ["infinity"]
          workingDir: "/"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1 # requesting 1 GPU
