apiVersion: v1
kind: Pod
metadata:
  name: rer-savia-llm
  namespace: rer-savia
spec:
  containers:
    - command: ["/bin/sh","-c"]
      args: ["sleep infinity"]
      image: harbor-core.prod.margherita.ad.lepida.it/savia-test/test_savia_llm:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      volumeMounts:
      - mountPath: /checkpoints
        name: checkpoints
      - mountPath: /LLM
        name: llm
      name: savia-test-llm
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        limits:
          nvidia.com/gpu: 1
          memory: 30Gi
          cpu: "16"
        requests:
          memory: 8Gi
          cpu: "8"
  volumes:
  - name: checkpoints
    persistentVolumeClaim: 
      claimName: checkpoints
  - name: llm
    persistentVolumeClaim: 
      claimName: llm
  metadata:
    namespace: rer-savia
  runtimeClassName: nvidia
