apiVersion: v1
kind: Pod
metadata:
  name: rer-savia-mongo
  namespace: rer-savia
spec:
  containers:
    - command: ["/bin/sh","-c"]
      args: ["sleep infinity"]
      image: harbor-core.prod.margherita.ad.lepida.it/savia-test/mongo
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 27017
      volumeMounts:
      - mountPath: /data/db
        name: savia-db
      name: savia-test-mongo
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        limits:
          memory: 30Gi
          cpu: "16"
        requests:
          memory: 8Gi
          cpu: "8"
  volumes:
  - name: savia-db
    persistentVolumeClaim: 
      claimName: savia-db
  metadata:
    namespace: rer-savia
  runtimeClassName: nvidia
