apiVersion: v1
kind: Pod
metadata:
  name: rer-savia-popola-volumi
  namespace: rer-savia
spec:
  containers:
    - command: ["/bin/sh","-c"]
      args: ["while true; do echo ''; sleep 60; done"]
      image: harbor-core.prod.margherita.ad.lepida.it/savia-test/savia-test-repo:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /python_client
        name: python-client
      - mountPath: /checkpoints
        name: checkpoints
      - mountPath: /llm
        name: llm
      - mountPath: /retriever
        name: retriever
      - mountPath: /data/db
        name: savia-db
      - mountPath: /savia-vector-stores
        name: savia-vector-stores
      name: savia-test-volume
      securityContext:
        privileged: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      resources:
        limits:
          memory: 30Gi
          cpu: "16"
        requests:
          memory: 8Gi
          cpu: "8"
  volumes:
  - name: python-client
    persistentVolumeClaim: 
      claimName: python-client
  - name: checkpoints
    persistentVolumeClaim: 
      claimName: checkpoints
  - name: llm
    persistentVolumeClaim: 
      claimName: llm
  - name: retriever
    persistentVolumeClaim: 
      claimName: retriever
  - name: savia-db
    persistentVolumeClaim: 
      claimName: savia-db
  - name: savia-vector-stores
    persistentVolumeClaim: 
      claimName: savia-vector-stores
  
  metadata:
    namespace: rer-savia
  runtimeClassName: nvidia
